### ISSUE TITLE
Modifying or adapting one script

### ISSUE THREAD

**Issue by LibertyType** [danielgamage/Glyphs-Scripts#2]
Would it be a lot of trouble to modify or adapt Convert to Lines.py so that it does not delete the control points? What would be even better (for me) would be for the script to change all curve nodes in a glyph that aren't perfectly vertical or horizontal.

**Comment by danielgamage** [comment]
@MajusCorp can you post a test case for me? just two screenshots of your glyphs window showing an original glyph and what the script should do to the glyph (i.e. before and after states)

**Comment by LibertyType** [comment]
Top image is 'After'; bottom one is 'Before'.
![screen shot after](https://user-images.githubusercontent.com/2348503/29030014-42b575c0-7b4f-11e7-9e37-83b67f43b8ae.png)
![screen shot before](https://user-images.githubusercontent.com/2348503/29030018-4595f49a-7b4f-11e7-98a4-39f5485b644f.png)

**Comment by danielgamage** [comment]
ah sure i don't _think_ this should be too hard. i would need to dig into the python docs again but i think you just need to add a couple lines that would only run the conversion on `SMOOTH` points

**EDIT**: i see now that the other condition is that they're vertical / horizontal nodes. i seem to remember the API having an `angleOfNode` property or similar. maybe you could take a look at the script i have and try adapting it using the Glyphs Macro panel

**Comment by LibertyType** [comment]
I'm not sure now that I need this. Anyway, I'm not a programmer so I wouldn't know where to begin modifying a script. For now I'm going to close my request.
